### ISSUE TITLE
Need a way to not encode query parameter names.

### ISSUE THREAD

**Issue by estaub** [dispatch/reboot#103]
AFAICT, there's no reasonable way to use a query parameter name with a character in it that _could_ be URL-encoded, but _must not_ be.  This is a problem with sites that require an unencoded name.  In my case, the problem arises with parameter names with "$" in them, as in both the Bing APIs and with Socrata's public open data API.  I've found at least three other people who have run into similar problems due to uncontrollable encoding on the mailing list, including one who used [heroic measures](https://bhudgeons.telegr.am/blog_posts/handling-non-standard-urls-in-dispatch) to work around it.

I've tried numerous workarounds, setting "useRaw" flags in AsyncHttpClient, etc.  Given that the other folks didn't get a good workaround when they posted on the mailing list, I'm just creating an issue straightaway (though I also have [a StackOverflow post](http://stackoverflow.com/questions/28972853/in-scala-dispatch-is-there-any-way-to-not-encode-query-parameters) up).

**Comment by farmdawgnation** [comment]
Thanks for mentioning this issue. I'm sorry it took so long to get a decent answer to it. I'm working on improving the turn-around time on support requests for Dispatch since I took over as maintainer.

I'm going to investigate this for 0.14.x, but cannot do it for earlier versions since it would, I suspect, be a breaking API change.

**Comment by estaub** [comment]
@farmdawgnation I'm no longer using Scala even, so don't give this any weight on my account!

**Comment by farmdawgnation** [comment]
Did some research on this.

For the moment it looks like you could get away with shenanigans like this by doing it directly in the URL. Example from the blog post:

```scala
@ url("http://api.sillyco.com/service?blue&$yellow").url
res3: String = "http://api.sillyco.com/service?blue&$yellow"
```

Admittedly, this isn't great.

Unfortunately, this is something that AsyncHttpClient is doing so if this is going to be fixed it'll require an issue to be filed [there](https://github.com/AsyncHttpClient/async-http-client/issues).

I'm going to close this since there's not much that Dispatch itself can do to resolve this use case. Feel free to comment back if there are any other questions.
