### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by haggy** [dispatch/reboot#126]
Hi there!

First, I want to thank you for making the seemingly only sane scala HTTP client available. Second, I noticed that the activity level on the project has been kind of low lately. We are using this lib in a couple scala apps where I work and I wanted to make sure that the project will continue to be supported and that there are no plans to deprecate/remove it from maven. Like I said we LOVE this lib. We spent over 2 hours yesterday investigating other scala HTTP clients and they are all very hard to work into projects where abstraction is key (kind of a weird statement but there it is). Thanks again and look forward to hearing from you!

**Comment by mdedetrich** [comment]
I don't think there has been much work simply because the library already does everything very well, and since it abstracts over Netty's Async HTTP, that library pretty much takes care of all of the lower level details.

There are some issues which definitely need to be addressed though, but in its current state, dispatch pretty much does everything that you need it to do

**Comment by SethTisue** [comment]
except run on Scala 2.12; that's #134

**Comment by farmdawgnation** [comment]
Hi there,

I just came on as maintainer today and am going through old issues. This is a bit stale, so I'll go ahead and close this, but I'll reiterate that Dispatch itself is pretty complete. That said, I've got a few gaps in mind I know I want to close and I want to do some dependency bumping - but other than that there's not a ton to do in my mind. =)

Cheers!
