### ISSUE TITLE
Add support for Dotty

### ISSUE THREAD

**Issue by Sciss** [dispatch/reboot#234]
Please publish a version for Scala 3.0.0-M2. Thank you!

**Comment by farmdawgnation** [comment]
Hey @Sciss — thanks for the request. That's going to be dependent on all of our dependencies being updated for Scala 3.0.0-M2, which I doubt they all are. I'll take a look at it though.

**Comment by Sciss** [comment]
Sure, just keep it as a bookmark

**Comment by sv3ndk** [comment]
Hi all, 

I'm in the process of upgrading my skills to scala 3, and as in order to get some real world practice I decided to try to upgrade the Disptach library to scala 3 and see how far I could go.

I currently have a WIP branch which compiles for 2.12., 2.13 and 3.1. I've not started working on the tests yet, and they currently fail, although I'm confident I'll get them working shortly. 

All of the libraries this project depends on seem to be available for Scala 3, except lift-json, so `dispatch-lift-json` is currently only built for 2.12 and 2.13. 

Would you be interested in a PR when my branch is ready? If you have any comments or suggestion, feel free to speak out :)



https://github.com/sv3ndk/reboot/tree/add_scala3_build

**Comment by sv3ndk** [comment]
Hi again, 

Just a quick update: the migration to scala 3 seems to be working on my branch (except for lift, cf above), all the UT are now green and I could use it successfully in a small toy project of mine based on Scala 3

**Comment by farmdawgnation** [comment]
@sv3ndk Been a minute since I've taken a look at issues here, but I'd be interested in a PR if this looks like it's working well!

**Comment by farmdawgnation** [comment]
Happy to report here that as of the Dispatch 2.0.0 release, we now officially support Scala 3.
