### ISSUE TITLE
Upgrade to AHC 3.0.0

### ISSUE THREAD

**Issue by maiflai** [dispatch/reboot#239]
**Problem statement**
AHC 3.0.0 has been released and contains breaking changes i.e. dispatch users cannot upgrade transitively.

* Timeouts are now passed as `java.time.Duration`
* oauth1 is no longer supported

**Proposed solution**
Upgrade Dispatch to support AHC 3.0.0 without retaining backwards compatibility.

Has anyone begun looking at this please?

**Comment by farmdawgnation** [comment]
I haven't been looking at this yet. I've done some experimentation, actually, with removing AHC from the build chain entirely in favor of Java's native http client, but ran into some other issues there so far. Ultimately it's been a bit since I've had time to work on this, but if AHC 3 is out I can take a look at updating the library.

**Comment by maiflai** [comment]
ah great, thanks very much. It looks relatively straightforward - does https://github.com/dispatch/reboot/pull/240 seem reasonable?

**Comment by farmdawgnation** [comment]
Yes, looks reasonable. I've left you a comment on there. I'm going to start thinking about how I want to package this up for release.

**Comment by farmdawgnation** [comment]
This has been incorporated into the 2.0.0 release, which is now live on maven central.

**Comment by maiflai** [comment]
great, thanks again!
