### ISSUE TITLE
Cannot decompress an encoded gzip stream

### ISSUE THREAD

**Issue by crockpotveggies** [dispatch/reboot#52]
Getting an encoded stream is rather common from big data APIs. Having a default handler similar to the basic `as.stream.Lines` would be really handy for this kind of use case.

Here's an example implementation to connect to a gzip encoded stream:

``````
Http(
      host("stream.data.com")
      .secure
      .addHeader("Accept-Encoding", "gzip")
       /  "streams" / "track" / "tweets.json"
      > as.stream.EncodedLines(println) )()```
``````

**Comment by farmdawgnation** [comment]
Filing this improvement for 0.14.x to start with. Depending on how invasive it ends up being I'll also consider backport for 0.13 and 0.12.

**Comment by farmdawgnation** [comment]
It looks like the AsyncHTTPClient has since added this functionality, so there's no need for us to do anything.

To use GZip compression in your connections, construct an http executor like so:

```scala
val myHttp = Http.withConfiguration(_.setCompressionEnforced(true).setKeepEncodingHeader(true))
```

Then you can use this executor like you normally would without having to account for gzip compression any differently.

```scala
myHttp(url(....) ....)
```

AsyncHttpClient will transparently handle the gzipping for you thanks to `setCompressionEnforced`. The `setKeepEncodingHeader` will preserve the `Content-Encoding` header for you to inspect after the fact if you choose to. If you don't care about that, you could omit it.

This is probably worth adding to the documentation, so I'll create a different issue for that. In any event, there's no actionable item for Dispatch's implementation so I'll close this out.
